#!/bin/bash
yum install -y aws-cli
yum install -y nano
yum install -y nfs-utils
yum update -y
mkdir /efs
mkdir /rcon
echo ECS_CLUSTER=${cluster} >> /etc/ecs/ecs.config
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 10.0.0.143:/ /efs
git clone https://github.com/barneygale/MCRcon.git /usr/local/mcrcon/
# stuff to rebuild
