#!/bin/bash
yum install -y aws-cli
yum install -y nano
yum install -y git
mkdir /vanilla-data
mkdir /rcon
echo ECS_CLUSTER=minecraft >> /etc/ecs/ecs.config
git clone https://github.com/alexkokkinos/aws-mc-scripts.git /usr/local/aws-mc-scripts/
git clone https://github.com/barneygale/MCRcon.git /usr/local/mcrcon/
chmod u+x /usr/local/aws-mc-scripts/s3sync.sh
aws s3 cp s3://saves-alex/vanilla-data/ /vanilla-data/ --recursive
echo "0 */12 * * * /usr/local/aws-mc-scripts/s3sync.sh" >> cronfile
crontab cronfile